import Head from 'next/head'
import Link from 'next/link'
import { Fade, Zoom } from 'react-reveal'
import YoutubeSVG from '../../assets/images/youtube.svg'

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="box-border h-screen w-full bg-red-100">
        <Fade right cascade>
          <div className="flex flex-col  justify-between pt-2 sm:flex-row ">
            <div className="mx-auto flex w-fit justify-center sm:mx-10 ">
              <img src={YoutubeSVG.src} className=" h-10" />
              <h1 className="my-auto mx-2 text-xl font-bold text-red-900">
                YTW
              </h1>
            </div>

            <div className="my-auto mx-auto text-lg sm:mr-14" id="mobile-menu">
              <ul className="flex flex-col text-center sm:flex-row  sm:space-x-8">
                <li>
                  <Link href="/" ariaCurrent="page">
                    <p className="cursor-pointer rounded-lg p-1 text-lg font-medium text-red-400 hover:bg-red-600 hover:text-white">
                      Home
                    </p>
                  </Link>
                </li>
                <li>
                  <Link href="/login">
                    <p className="cursor-pointer rounded-lg p-1 text-lg font-medium text-red-400 hover:bg-red-600 hover:text-white">
                      Explore
                    </p>
                  </Link>
                </li>
                <li>
                  <Link href="/about">
                    <p className="cursor-pointer rounded-lg p-1 text-lg font-medium text-red-400 hover:bg-red-600 hover:text-white">
                      About
                    </p>
                  </Link>
                </li>
                <li>
                  <Link href="/contact">
                    <p className="cursor-pointer p-1 text-lg font-medium text-red-600">
                      Contact
                    </p>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </Fade>
        <Zoom>
          <div className="mx-auto mt-10 w-full cursor-pointer rounded-lg bg-white p-10 shadow-md sm:w-2/3">
            <Fade left>
              <div className="mx-auto w-fit text-2xl font-medium text-red-700">
                Contact Us
              </div>
            </Fade>
            <Fade left>
              <div className="mt-10 text-center text-lg">
                Commodo aute nulla voluptate aliqua voluptate tempor duis et et
                consectetur.
              </div>
            </Fade>
          </div>
        </Zoom>
      </div>
    </>
  )
}
