import Head from 'next/head'
import Link from 'next/link'
import { Zoom } from 'react-reveal'
import Fade from 'react-reveal/Fade'
import YoutubeSVG from '../../assets/images/youtube.svg'
import aboutSVG from '../../assets/images/about.svg'

export default function About() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full bg-red-100 pb-20">
        <Fade right cascade>
          <div className="flex flex-col  justify-between pt-2 sm:flex-row ">
            <div className="mx-auto flex w-fit justify-center sm:mx-10 ">
              <img src={YoutubeSVG.src} className=" h-10" />
              <h1 className="my-auto mx-2 text-xl font-bold text-red-900">
                YTW
              </h1>
            </div>

            <div className="my-auto mx-auto text-lg sm:mr-14" id="mobile-menu">
              <ul className="flex flex-col text-center sm:flex-row  sm:space-x-8">
                <li>
                  <Link href="/">
                    <p className="cursor-pointer rounded-lg p-1 text-lg font-medium text-red-400 hover:bg-red-600 hover:text-white">
                      Home
                    </p>
                  </Link>
                </li>
                <li>
                  <Link href="/login">
                    <p className="cursor-pointer rounded-lg p-1 text-lg font-medium text-red-400 hover:bg-red-600 hover:text-white">
                      Explore
                    </p>
                  </Link>
                </li>
                <li>
                  <Link href="/about" ariaCurrent="page">
                    <p className="cursor-pointer p-1 text-lg font-medium text-red-600">
                      About
                    </p>
                  </Link>
                </li>
                <li>
                  <Link href="/contact">
                    <p className="cursor-pointer rounded-lg p-1 text-lg font-medium text-red-400 hover:bg-red-600 hover:text-white">
                      Contact
                    </p>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </Fade>

        <Zoom>
          <div className="mx-auto mt-10 w-full cursor-pointer rounded-lg bg-white p-10 shadow-md sm:w-2/3">
            <Fade left>
              <div className="mx-auto w-fit text-2xl font-medium text-red-700">
                About Youtube Wrapped !
              </div>
            </Fade>
            <Fade right>
              <img src={aboutSVG.src} alt="about" className=" mx-auto mt-10" />
            </Fade>
            <Fade left>
              <div className="mt-10 text-center text-lg">
                Commodo aute nulla voluptate aliqua voluptate tempor duis et et
                consectetur. Lorem eu irure consequat tempor magna. Elit
                adipisicing consectetur occaecat veniam duis Lorem dolor.
                Laborum amet ea cupidatat aliqua nisi do in non pariatur.Commodo
                aute nulla voluptate aliqua voluptate tempor duis et et
                consectetur. Lorem eu irure consequat tempor magna. Elit
                adipisicing consectetur occaecat veniam duis Lorem dolor.
                Laborum amet ea cupidatat aliqua nisi do in non pariatur.Commodo
                aute nulla voluptate aliqua voluptate tempor duis et et
                consectetur. Lorem eu irure consequat tempor magna. Elit
                adipisicing consectetur occaecat veniam duis Lorem dolor.
                Laborum amet ea cupidatat aliqua nisi do in non pariatur.Commodo
                aute nulla voluptate aliqua voluptate tempor duis et et
                consectetur. Lorem eu irure consequat tempor magna. Elit
                adipisicing consectetur occaecat veniam duis Lorem dolor.
                Laborum amet ea cupidatat aliqua nisi do in non pariatur.Commodo
                aute nulla voluptate aliqua voluptate tempor duis et et
                consectetur. Lorem eu irure consequat tempor magna. Elit
                adipisicing consectetur occaecat veniam duis Lorem dolor.
                Laborum amet ea cupidatat aliqua nisi do in non pariatur.Commodo
                aute nulla voluptate aliqua voluptate tempor duis et et
                consectetur. Lorem eu irure consequat tempor magna. Elit
                adipisicing consectetur occaecat veniam duis Lorem dolor.
                Laborum amet ea cupidatat aliqua nisi do in non pariatur.Commodo
                aute nulla voluptate aliqua voluptate tempor duis et et
                consectetur. Lorem eu irure consequat tempor magna. Elit
                adipisicing consectetur occaecat veniam duis Lorem dolor.
                Laborum amet ea cupidatat aliqua nisi do in non pariatur.Commodo
                aute nulla voluptate aliqua voluptate tempor duis et et
                consectetur. Lorem eu irure consequat tempor magna. Elit
                adipisicing consectetur occaecat veniam duis Lorem dolor.
                Laborum amet ea cupidatat aliqua nisi do in non pariatur.
              </div>
            </Fade>
          </div>
        </Zoom>
      </div>
    </>
  )
}
