import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import YoutubeSVG from '../assets/images/youtube.svg'
import AnalyticsSVG from '../assets/images/hero_analytics_dark.svg'
export default function Home() {
  const [formData, setFormData] = useState({ username: '', password: '' })
  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value })
  }
  const handleSubmit = (e) => {
    e.preventDefault()
    console.log(formData)
  }
  return (
    <>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="box-border h-screen w-full bg-red-100">
        <div className="flex flex-col  justify-between pt-2 sm:flex-row ">
          <div className="mx-auto flex w-fit justify-center sm:mx-10 ">
            <img src={YoutubeSVG.src} className=" h-10" />
            <h1 className="my-auto mx-2 text-xl font-bold text-red-900">YTW</h1>
          </div>

          <div className="my-auto mx-auto text-lg sm:mr-14" id="mobile-menu">
            <ul className="flex flex-col text-center sm:flex-row  sm:space-x-8">
              <li>
                <Link href="/" ariaCurrent="page">
                  <p className="cursor-pointer p-1 text-lg font-medium text-red-600">
                    Home
                  </p>
                </Link>
              </li>
              <li>
                <Link href="/login">
                  <p className="cursor-pointer rounded-lg p-1 text-lg font-medium text-red-400 hover:bg-red-600 hover:text-white">
                    Explore
                  </p>
                </Link>
              </li>
              <li>
                <Link href="#">
                  <p className="cursor-pointer rounded-lg p-1 text-lg font-medium text-red-400 hover:bg-red-600 hover:text-white">
                    About
                  </p>
                </Link>
              </li>
              <li>
                <Link href="#">
                  <p className="cursor-pointer rounded-lg p-1 text-lg font-medium text-red-400 hover:bg-red-600 hover:text-white">
                    Contact
                  </p>
                </Link>
              </li>
            </ul>
          </div>
        </div>
        <div className="mx-auto rounded-lg bg-red-100 p-5 sm:w-1/2">
          <h1 className="mx-auto my-10 w-fit text-center text-3xl font-bold text-red-600 sm:text-6xl">
            Welcome To Youtube Wrapped
          </h1>
          <img src={AnalyticsSVG.src} className="w-full"></img>
        </div>
      </div>
    </>
  )
}
